KidsHealthCare/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from littleStar import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^littleStar/',include('littleStar.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

littleStar/urls.py
from django.conf.urls import url
from littleStar import views
from django.conf.urls.static import static
from django.conf import settings

# SET THE NAMESPACE!
app_name = 'littleStar'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^/$',views.index,name='index'),
    url(r'^index/$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^kidDetailsRedirect/$',views.detailRedirect,name='kidDetails'),
    url(r'^createSchool/$',views.createSchool,name='createSchool'),
    url(r'^anthropometry/$', views.anthropometryView, name = 'anthropometry'),
    url(r'^dental/$', views.dental, name = 'dental'),
    url(r'^pediatrics/$', views.pediatrics, name = 'pediatrics'),
    url(r'^nutrition/$', views.nutrition, name = 'nutrition'),
    url(r'^optomology/$', views.optomology, name = 'optomology'),
    url(r'^dummyAjaxCall/$', views.dummyAjaxCall, name = 'dummyAjaxCall'),
    url(r'^updateAnthropometryForm/$', views.updateAnthropometryForm, name = 'updateAnthropometryForm'),



    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

littleStar/views.py
from django.shortcuts import render
from littleStar.forms import UserForm,UploadFileForm,UserProfileInfoForm,schoolDetailsForm,kidDetailsForm,anthropometryForm,dentalForm,pediatricForm,nutritionForm,optholForm
import xlrd
from django.core.files.storage import FileSystemStorage
import datetime
from datetime import date
from django.contrib import messages
# from rest_framework.renderers import JSONRenderer
from django.core import serializers

from littleStar.models import kiddetails,CreateSchool,UserProfileInfo,anthropometry,Dental,Pediatrics,Nutrition,Opthol
from django.shortcuts import redirect


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    
    return render(request,'littleStar/index.html')


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))
 
def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

            userSuccessCreationMessage = 'DR '+ str(user) + ' profile has been created'
            
            messages.success(request, userSuccessCreationMessage)

            user_form = UserForm()
        
            profile_form = UserProfileInfoForm()

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'littleStar/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered,
                           })

def user_login(request):
    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)
        
        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)


                #cookie set on login to know the doctor specialization thorugh out
                sessionForDoctorSpecialization = UserProfileInfo.objects.get(user = user )
                request.session['doctorSpecialization'] = sessionForDoctorSpecialization.doctorSpecialization


                # Send the user back to some page.
                # In this case their homepage.
                return render(request, 'littleStar/index.html')
                #return render(request, 'littleStar/index.html',{'doctorSpecialization':doctorSpecialization})
            else:
                # If account is not active:
                return render(request, 'littleStar/login.html',{
                'login_message' : 'The user has been removed',})
        else:
            return render(request, 'littleStar/login.html',{
                'login_message' : 'You have entered the wrong credentials',})

    else:
        #Nothing has been provided for username or password.`
        return render(request, 'littleStar/login.html')

def calculate_age(born):
    today = date.today()
    try: 
        birthday = born.replace(year=today.year)
    except ValueError: # raised when birth date is February 29 and the current year is not a leap year
        birthday = born.replace(year=today.year, month=born.month+1, day=1)
    if birthday > today:
        return today.year - born.year - 1
    else:
        return today.year - born.year

def createSchool(request):
    duplicateList = []
    #checking for excel upload
    if request.method == 'POST' and request.FILES['excel']:

        #creating the model instance of the scool directly to get rid of form valdiations
        schoolDetailsUpload = CreateSchool()

        #creating the new data for the table
        schoolDetailsUpload.schoolName = request.POST.get('schoolname')
        schoolDetailsUpload.schoolUID = request.POST.get('schooluid')
        schoolDetailsUpload.schoolAddress = request.POST.get('schoolAddress')
        schoolDetailsUpload.principalName = request.POST.get('principalName')
        schoolDetailsUpload.schoolContact = request.POST.get('schoolContactNumber')

        schoolUidDuplicate = CreateSchool.objects.filter(schoolUID = schoolDetailsUpload.schoolUID )

        if not schoolUidDuplicate:
            #saving data to data base
            schoolDetailsUpload.save()
                #getting the data of the excel in to a variable for parsing
            myfile = request.FILES['excel']

            #using xlrd to parse the exel file
            book = xlrd.open_workbook(myfile.name)

            #getting thwe book sequence to the first
            sheet = book.sheet_by_index(0)

            #looping through all the table rows
            for r in range(1,sheet.nrows):

                #getting the new modal instance every time for new student
                article = kiddetails()

                #assinging the table data to the data table rows directly: bypassing form

                article.childname = sheet.cell(r,0).value
                localDateTime =  sheet.cell(r,1).value
                article.dob	=  datetime.datetime(*xlrd.xldate_as_tuple(sheet.cell(r,1).value, book.datemode))
                article.sex	= sheet.cell(r,2).value
                article.fathername =sheet.cell(r,3).value
                article.fatherphonenumber = sheet.cell(r,4).value
                article.fatheremail = sheet.cell(r,5).value
                article.mothername = sheet.cell(r,6).value
                article.motherphonenumber = sheet.cell(r,7).value
                article.motheremail  = sheet.cell(r,8).value
                article.address  = sheet.cell(r,9).value
                article.teachername = sheet.cell(r,10).value
                article.teacheremail  = sheet.cell(r,11).value
                article.age  = calculate_age(datetime.datetime.date(article.dob))
                article.childuid = article.childname[:3].upper() + article.mothername[:3].upper() + str(datetime.datetime.date(article.dob)).split('-')[0][2:]
                article.schooluid =  CreateSchool.objects.get(schoolUID= request.POST.get('schooluid'))
            
                #saving data to data base
              
                kidDuplicate = kiddetails.objects.filter(childuid = article.childuid )
                if not kidDuplicate:
                    article.save()
                else:
                    duplicateList.append(article.childname)
        
        else:
            messages.success(request,"School UID already Exists, Please try another")
    
        messages.success(request,duplicateList)
        return render(request, 'littleStar/createSchool.html')
    return render(request, 'littleStar/createSchool.html')



def detailRedirect(request):
    prefillDetails = {}
    if request.method == 'POST':
        kidUID = request.POST.get('kidDetails')

        try:
            kidIndividualDetails = kiddetails.objects.get(childuid = kidUID )

        except kiddetails.DoesNotExist:
            kidIndividualDetails=None

        else:
            print ("Apress is in the database.")

        if not kidIndividualDetails:
            messages.success(request,'Invalid UID')
            return HttpResponseRedirect(reverse('index'))
        else:

            # To know the specality of doctor so that we can navigate to right page
            if request.session.has_key('doctorSpecialization'):
                doctorSpecialization = request.session['doctorSpecialization'].strip()

            #if doctor belongs to anthropometry
            if (doctorSpecialization == 'anthropometry'):
                kidsAntropometry = navigateToAnthropomentry(request.POST.get('kidDetails'))

                if (kidsAntropometry is not None):
                    return render(request,'littleStar/formCompleted.html',{'kidUID':kidIndividualDetails,'doctorSpecialization':doctorSpecialization})
                else:
                    return render(request,'littleStar/anthropometry.html',{'kidUID':kidIndividualDetails,'doctorSpecialization':doctorSpecialization})


            #if doctor belongs to dental
            if (doctorSpecialization == 'dental'):
                kidsDental = checkDentalRecord(request.POST.get('kidDetails'))

                dental_form = dentalForm(data=request.POST)

templates/littleStar/anthropometry.html
{% extends 'littleStar/base.html' %}{% load static %} {% block body_block %}
<div class="container">
   <div class="col-lg-12">
      <div class="row kidPersonalDetails">
         <div class="col-lg-2">
            <p class="titles">
               <strong>UID:</strong>
            </p>
            <p class="uidDisplay" id="uidDisplay">{{kidUID.childuid}}</p>
         </div>
         <div class="col-lg-2">
            <p class="titles">
               <strong>Name:</strong>
            </p>
            <p> {{kidUID.childname}}</p>
         </div>
         <div class="col-lg-2">
            <p class="titles">
               <strong>Date of Birth:</strong>
            </p>
            <p>{{kidUID.dob}}</p>
            <p class="titles">
                  <strong>Age:</strong>
               </p>
               <p class="convertedAge">{{kidUID.age}}</p>
         </div>
         <div class="col-lg-2">
            <p class="titles">
               <strong>Father's Name:</strong>
            </p>
            <p>{{kidUID.fathername}}</p>
         </div>
         <div class="col-lg-2">
            <p class="titles">
               <strong>Mother's Name:</strong>
            </p>
            <p>{{kidUID.mothername}}</p>
         </div>
         <div class="col-lg-2">
            <p class="titles">
               <strong>Sex:</strong>
            </p>
            <p>{{kidUID.sex}}</p>
         </div>
      </div>
   </div>
   <form enctype="multipart/form-data" class="" method="POST" action="{% url 'littleStar:anthropometry' %}"
   novalidate id="anthropometryForm">
   {% csrf_token %}
   <div class="col-lg-12">
      <div class="row kidDetailsForms">
         <p class="loginHeader">Anthropometry</p>
         <div class="anthromentryFromToBeShown">
            <div class="col-lg-6">
               <div class="bmiHolder">
                  <p class="bmiTitle">
                     <strong>BMI:</strong>
                  </p><br>
                  <p id="calculatedBMI">0</p>
               </div>
               <div class="bmiHolder">
                  <p class="bmiTitle">
                     <strong>BSA:</strong>
                  </p><br>
                  <p id="calculatedBSA">0</p>
               </div>
            </div>
           
               <div class="col-lg-6">
                     <div class="row">
                  <div class="input-field">
                     <label for="id_HEIGHT">HEIGHT:</label>
                     <input type="number" name="height" required="" value="{{anthropometry_form.height}}"
                        id="id_HEIGHT"> 
                  </div>
               </div>
               <div class="row">
                  <div class="input-field">
                     <label for="id_WEIGHT">WEIGHT:</label>
                     <input type="number" name="weight" required="" id="id_WEIGHT" value="{{anthropometry_form.weight}}"> 
                  </div>
               </div>
               <div class="row">
                  <div class="input-field">
                     <label for="id_HEAD_CIRCUMFERENCE">HEAD CIRCUMFERENCE:</label>
                     <input type="number" name="headcircumference" required="" id="id_HEAD_CIRCUMFERENCE"
                        value="{{anthropometry_form.headcircumference}}"> 
                  </div>
               </div>
               <div class="row">
                  <div class="input-field">
                     <label for="id_MID_UPPER_ARM_CIRCUMFERENCE">MID UPPER ARM CIRCUMFERENCE:</label>
                     <input type="number" name="midupperarmcircumference" required=""
                        value="{{anthropometry_form.midupperarmcircumference}}" id="id_MID_UPPER_ARM_CIRCUMFERENCE"> 
                  </div>
               </div>
               <div class="row">
                  <div class="input-field">
                     <label for="id_TRICEP_SKIN_FOLDNESS">TRICEP SKIN FOLDNESS:</label>
                     <input type="number" name="tricepskinfoldness" required="" id="id_TRICEP_SKIN_FOLDNESS"
                        value={{anthropometry_form.tricepskinfoldness}}> 
                  </div>
               </div>
               <div class="row" style="display: none;">
                  <div class="input-field">
                     <label for="id_BMI">BMI:</label>
                     <input type="text" name="bmi" required="" id="id_BMI" maxlength="245" value="{{anthropometry_form.bmi}}"> 
                  </div>
               </div>
               <div class="row" style="display: none;">
                  <div class="input-field">
                     <label for="id_BSA">BSA:</label>
                     <input type="text" name="bsa" required="" id="id_BSA" maxlength="245" value={{anthropometry_form.bsa}}> 
                  </div>
               </div>
               <div class="row" style="display: none;">
                  <div class="input-field">
                     <label for="id_YEAR">YEAR:</label>
                     <input type="text" name="year" required="" id="id_YEAR" maxlength="245" value={{anthropometry_form.year}}> 
                  </div>
               </div>
               <div class="row" style="display: none;">
                  <div class="input-field">
                     <label for="id_kidUid">KidUid:</label>
                     <input type="text" name="kiduid" required="" id="id_kidUid" maxlength="245" value={{anthropometry_form.kiduid}}> 
                  </div> 
               </div>
               </div>
              
         </div>
      </div>
   </div>
   <div class="col-lg-12">
      <div class="row kidDetailsForms">
         <p class="loginHeader">Vitals</p>
        
         <div class="col-lg-6">
            <div class="row">
               <div class="input-field">
                  <label for="id_heartrate">Heart Rate:</label>
                  <input type="number" name="heartrate" required="" id="id_heartrate"
                     value=''> 
               </div>
            </div>
            <div class="row">
               <div class="input-field">
                  <label for="id_temparature">Temparature:</label>
                  <input type="number" name="temparature" required="" id="id_temparature"
                     value=''> 
               </div>
            </div>
            <div class="row">
                        <div class="input-field">
                           <label for="id_respiratoryrate">Respiratoy Rate:</label>
                           <input type="number" name="respiratoryrate" required="" id="id_respiratoryrate"
                              value=''> 
                        </div>
                     </div>
            <div class="row">
               <div class="input-field">
                  <label for="id_saturation">Saturation:</label>
                  <input type="number" name="saturation" required="" id="id_saturation"
                     value=''> 
               </div>
            </div>
            <div class="row">
               <div class="input-field">
                  <label for="id_bloodpressure1">Blood Pressure1:</label>
                  <input type="text" name="bloodpressure1" required="" id="id_bloodpressure1"
                     value=''> 
               </div>
            </div>
            <div class="row">
                  <div class="input-field">
                     <label for="id_bloodpressure2">Blood Pressure2:</label>
                     <input type="text" name="bloodpressure2" required="" id="id_bloodpressure2"
                        value=''> 
                  </div>
               </div>
               <div class="row">
                  <div class="input-field">
                     <label for="id_bloodpressure3">Blood Pressure3:</label>
                     <input type="text" name="bloodpressure3" required="" id="id_bloodpressure3"
                        value=''> 
                  </div>
               </div>
               <div class="row">
                  <button type="button"  id="calculateBp" class="btn btn-warning">Take BP average</button>
                  
               </div>
            <div class="row" style="display: none;">
               <div class="input-field">
                  <label for="id_systolic">Systolic:</label>
                  <input type="number" name="systolic" required="" id="id_systolic"
                     value=''> 
               </div>
            </div>
            <div class="row" style="display: none;">
               <div class="input-field">
                  <label for="id_diastolic">Diastolic:</label>
                  <input type="number" name="diastolic" required="" id="id_diastolic"
                     value=''> 
               </div>
            </div>
            <div class="row" style="display: none;">
                        <div class="input-field">
                           <input type="" name="sign" required="" id="anthroSign"
                              value=''> 
                        </div>
                     </div>
         </div>
         <div class="col-lg-6">
            <div class="bmiHolder">
               <p class="bmiTitle">
                  <strong>Systolic:</strong>
               </p><br>
               <p id="calculatedSystolic">0</p>
            </div>
            <div class="bmiHolder">
               <p class="bmiTitle">
                  <strong>Diastolic:</strong>
               </p><br>
               <p id="calculatedDiastolic">0</p>
            </div>
         </div>
      </div>
   </div>
   <button type="submit" name="" class="loginSubmit">Create </button>
</form>
</div>
{% endblock %}

templates/littleStar/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>Little Star</title>
  <meta content="width=device-width,initial-scale=1" name=viewport>
  <!-- Latest compiled and minified CSS -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,500" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  " rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}"> </head>

<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a class="navbar-link" href="{% url 'index' %}">Home</a>
          </li> {% if request.user.is_superuser %}
          <li>
            <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'littleStar:createSchool' %}">Create School</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'littleStar:register' %}">Create Doctor Access</a>
          </li> {% endif %}{# Some logic on what to display for last item#} {% if user.is_authenticated %}
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li> {% else %}
          <li>
            <a class="navbar-link" href="{% url 'littleStar:user_login' %}">Login</a>
          </li> {% endif %}
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="#">Action</a>
              </li>
              <li>
                <a href="#">Another action</a>
              </li>
              <li>
                <a href="#">Something else here</a>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="#">Separated link</a>
              </li>
            </ul>
          </li> -->
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav> {% block body_block %} {% endblock %}
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    
  <script src="{% static 'js/main.js' %}"></script>

</html>

templates/littleStar/createSchool.html
{% extends 'littleStar/base.html' %} {% block body_block %}
<div class="loginContainer">
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="loginFormContainer"> {% if messages %}
                    <ul class="messages orangeErrorMessage errorMessage ">
                        <P>WE HAVE THE FOLLOWING DUPLICATE LIST</P> {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"
                            {% endif %}>{{ message }}</li> {% endfor %} </ul> {% endif %}
                    <form method="post" action="{% url 'littleStar:createSchool' %} "
                        enctype="multipart/form-data"> {% csrf_token %}
                        <p class="loginHeader">CREATE SCHOOL DETAILS</p>
                        <div class="row">
                            <div class="input-field">
                                <!-- <label for="username">Username:</label> -->
                                <input type="text" name="schoolname" required placeholder="Name of the school"> </div>
                        </div>
                        <div class="row">
                            <div class="input-field">
                                <!-- <label for="username">Username:</label> -->
                                <input type="text" name="schooluid" required placeholder="Create a Unique school id"> </div>
                        </div>
                        <div class="row">
                            <div class="input-field">
                                <!-- <label for="username">Username:</label> -->
                                <input type="text" name="schoolAddress" required placeholder="Address of the school"> </div>
                        </div>
                        <div class="row">
                            <div class="input-field">
                                <!-- <label for="username">Username:</label> -->
                                <input type="text" name="principalName" required placeholder="Name of the Principal"> </div>
                        </div>
                        <div class="row">
                            <div class="input-field">
                                <!-- <label for="username">Username:</label> -->
                                <input type="text" name="schoolContactNumber" required placeholder="School Contact Number"> </div>
                        </div>
                        <div class="row ">
                            <div class="input-field ">
                                <label for="excel ">Upload Kid Details Excel in the specified Format</label>
                                <br/>
                                <input type="file" name="excel"> </div>
                        </div>
                        <input type="submit" class='loginSubmit' name=" " value="Create School Data" /> </form>
                    <div class="clearFLoats"></div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
</div>{% endblock %}

templates/littleStar/index.html
<div class="homeContainer "> {% extends "littleStar/base.html" %} {% block body_block %}{% load static %}
  <div class="clearFLoats"></div>
  <div class="container">
    <div class="welcomeHomeNotes col-md-6"> {% if user.is_authenticated %}
      <!-- ! is from {{ doctorSpecialization }}-->
      <p class="welcomeLoginHeading">Welcome {{ user.username }}</p>
      <br/> {% if messages %}
      <ul class="messages orangeErrorMessage errorlist "> {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li> {% endfor %} </ul> {% endif %}
      <form method="post" action="{% url 'littleStar:kidDetails' %}">
      {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" id="searchKid" placeholder="Search with kid UID" name="kidDetails" required> </div>
        <button type="submit" class="btn btn-default">Search</button>

      </form> {% else %}
      <p class="welcomeHeading">Welcome </p>
      <p class="welcomeFollowedText">to Student Health Program!</p> {% endif %} </div>
    <div class="col-md-6">
      {% comment %} <img src="{% static 'images/happy-kids-clipart-transparent.png' %}" class="homePageImage img-responsive" />  {% endcomment %}
    </div>
  </div>

 
</div> {% endblock %} 

templates/littleStar/login.html
{% extends 'littleStar/base.html' %} {% block body_block %}
<div class="loginContainer">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="loginFormContainer"> {% if login_message %}
          <p class="bg-primary errorMessage">{{ login_message }}</p> {% endif%}
          <form method="post" action="{% url 'littleStar:user_login' %} "> {% csrf_token %}
            <p class="loginHeader">LOGIN</p>
            <div class="row">
              <div class="input-field">
                <!-- <label for="username">Username:</label> -->
                <input type="text" name="username" required placeholder="EMAIL"> </div>
            </div>
            <div class="row">
              <div class="input-field">
                <!-- <label for="password">Password</label> -->
                <input type="password" name="password" required placeholder="PASSWORD"> </div>
            </div>
            <p class="passwordHelpText"> CONTACT ADMIN INCASE OF FORGOT PASSWORD.</p>
            <input type="submit" class='loginSubmit' name="" value="SIGN IN"
              class=""> </form>
          <div class="clearFLoats"></div>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>{% endblock %}

templates/littleStar/registration.html
{% extends "littleStar/base.html" %} {% load staticfiles %} {% block body_block %}
<div class="loginContainer">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="loginFormContainer">
          <p class="loginHeader">CREATE DOCTOR ACCESS</p> {% if registered %} {% if messages %}
          <ul class="messages orangeErrorMessage errorMessage ">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li> {% endfor %} </ul> {% endif %} {% endif%}
          <form enctype="multipart/form-data" method="POST"
            id="registerForm"> {% csrf_token %} {% for field in user_form %}
            <div class="row">
              <div class="input-field"> {{ field.errors }} {{ field.label_tag }} {{ field }} </div>
            </div> {% endfor %} {% for field in profile_form %}
            <div class="row">
              <div class="input-field">
                <p>Choose the specialization:</p>
                <div class="select-wrapper">{{ field.errors }} {{ field }}</div>
              </div>
            </div> {% endfor %}
            <button type="submit" name="" class="loginSubmit">Create </button>
          </form>
          <div class="clearFLoats"></div>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div> {% endblock %}